version: '3.7'
services:
    filed:
        build:
            context: filed
            dockerfile: Dockerfile.dev
        networks:
            bfile:
        volumes:
            - './filed:/opt/code'
            - '/opt/code/target'
            - './volatile/files:/opt/user_uploads'
    caddy:
        image: caddy:alpine
        volumes:
            - './conf/caddy:/etc/caddy:ro'
        ports:
            - 80:80
        networks:
            bfile:
    redis:
        image: redis:alpine
        networks:
            bfile:
        command: [ 'redis-server', '--requirepass', '$REDIS_PASS' ]
        ports:
            - 6379:6379
        
networks:
    bfile: