version: '3.7'
services:
    filed:
        build:
            context: .
            dockerfile: filed/Dockerfile.prod
        networks:
            bfile:
        volumes:
            - './filed:/config:ro'
            - './filed/config:/etc/filed:ro'
            - './volatile/files:/opt/user_uploads'
    janitord:
        build:
            context: janitor
            dockerfile: Dockerfile.prod
        networks:
            bfile:
        volumes:
            - './janitor:/config:ro'
            - './volatile/files:/opt/user_uploads'
    resourced:
        build:
            context: resource
            dockerfile: Dockerfile.prod
        networks:
            bfile:
        pid: host # prefork
        volumes:
            - './resource:/opt/cont'
    caddy:
        image: caddy:alpine
        volumes:
            - './conf/caddy:/etc/caddy:ro'
        ports:
            - 80:80
        networks:
            bfile:
    redis:
        image: redis:alpine
        networks:
            bfile:
        command: [ 'redis-server', '--requirepass', '$REDIS_PASS' ]
        ports:
            - 6379:6379
    qr:
        image: blekii/miniqr
        networks:
            bfile:

networks:
    bfile: