# --- build ---
FROM rust as builder

WORKDIR /opt/code
COPY . .

RUN apt install -y git

# No build is done during this step
# since the directory will be mounted anyways
# to the dev's machine.

# Therefore installing & compiling in the dockerfile
# would be moronic, to say at least

# However, cargo watch needs to be installed
RUN cargo install cargo-watch

CMD [ "/opt/code/dev-entry.sh" ]
