# --- build ---
FROM rust as builder

WORKDIR /opt/code
COPY . .

# No build or install is done during this step
# since the directory will be mounted anyways
# to the dev's machine.

# Therefore installing & compiling in the dockerfile
# would be moronic, to say at least

CMD [ "dev-entry.sh" ]
