# --- build ---
FROM rust:alpine as builder

WORKDIR /opt/build
COPY . .

RUN apk add --no-cache musl-dev upx nodejs yarn && \
    yarn global add uglify-js

RUN cargo b -r
RUN strip target/release/filed && upx --best target/release/filed

# --- deploy ---
FROM busybox:musl

RUN mkdir /config
WORKDIR /config

COPY --from=builder /opt/build/target/release/filed /bin/filed
CMD [ "/bin/filed" ]
